proxy:
  secretToken: "c413fe27d65c5916b7cf4028bf49a19b3056d59f2c2d1e79349244a6f758babe"

hub:
  config:
    JupyterHub:
      authenticator_class: dummy

singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 1Gi
    dynamic:
      pvcNameTemplate: claim-{username}
      storageAccessModes: ["ReadWriteOnce"]
  memory:
    guarantee: 512Mi
    limit: 1Gi
  cpu:
    guarantee: 0.5
    limit: 1
  profileList:
    - display_name: "CPU Server"
      description: "Node worker biasa"
      kubespawner_override:
        image: danielcristh0/jupyterlab:1.1
        cpu_limit: 1
        mem_limit: 1G
    - display_name: "GPU Server"
      description: "Jalankan di node head dengan GPU"
      kubespawner_override:
        image: danielcristh0/jupyterlab:1.1
        cpu_limit: 2
        mem_limit: 3G
        extra_resource_limits:
          nvidia.com/gpu: "1"