hub:
  config:
    JupyterHub:
      authenticator_class: dummy
      shutdown_on_logout: true
      bind_url: http://0.0.0.0:8081
    KubeSpawner:
      k8s_api_request_timeout: 60
      start_timeout: 300
      http_timeout: 300
    Authenticator:
      admin_users:
        - admin

  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 6

  db:
    url: sqlite:////data/jupyterhub.sqlite

  service:
    type: ClusterIP

  extraVolumes:
    - name: jupyterhub-db
      persistentVolumeClaim:
        claimName: jupyterhub-pvc

  extraVolumeMounts:
    - name: jupyterhub-db
      mountPath: /data

proxy:
  secretToken: "c413fe27d65c5916b7cf4028bf49a19b3056d59f2c2d1e79349244a6f758babe"
  https:
    enabled: false
  service:
    type: ClusterIP

singleuser:
  image:
    name: "danielcristh0/jupyterlab"
    tag: "1.1"
    pullPolicy: Always
  defaultUrl: "/lab"
  storage:
    capacity: 1G
    dynamic:
      pvcNameTemplate: claim-{username}
      storageAccessModes: ["ReadWriteOnce"]
  memory:
    guarantee: 512M
    limit: 1G
  cpu:
    guarantee: 0.5
    limit: 1

cull:
  enabled: true                # Enable culling of idle JupyterLab servers
  timeout: 1800                # Timeout in seconds before stopping an idle server (30 minutes)
  every: 60                    # Interval in seconds to check for idle servers (1 minute)
  maxAge: 0                    # Maximum age of a server in seconds; 0 means no age limit
  users: false                 # Do not cull users from the Hub, only their servers
  removeNamedServers: false   # Do not remove named servers when culling

