# see https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster
# and https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/config.html
image:
  repository: danielcristh0/ray
  tag: rpl
  pullPolicy: Always

head:
  enableInTreeAutoscaling: true
  rayStartParams:
    # don't use head node for scheduling
    # as per https://github.com/ray-project/kuberay/blob/master/docs/best-practice/worker-head-reconnection.md#best-p>
    num-cpus: 0
    num-gpus: 0
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
      nvidia.com/gpu: 1
    requests:
      cpu: "4"
      memory: "8Gi"
      nvidia.com/gpu: 1

worker:
  minReplicas: 1
  maxReplicas: 3
  rayStartParams:
    num-cpus: "2"
    num-gpus: "0"
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "2"
      memory: "4Gi"