version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/infra/docker/jupyterlab"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "pip"
    directory: "/infra/docker/ray"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "pip"
    directory: "/ray-projects"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"

