---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker

- name: Install Docker-Compose & Set Permission
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: Create Docker-Compose symlink
  ansible.builtin.command:
    cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    creates: /usr/bin/docker-compose

# - name: Configure private registry
#   ansible.builtin.template:
#     src: daemon.j2
#     dest: /etc/docker/daemon.json
#     mode: preserve

- name: Install NVIDIA Container Toolkit
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
    state: present

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Test GPU with Docker
  ansible.builtin.command:
    cmd: docker run --rm --gpus all nvidia/cuda:12.2.0-base-ubuntu22.04 nvidia-smi
  register: gpu_test
  ignore_errors: true

- name: Print GPU test result
  ansible.builtin.debug:
    var: gpu_test.stdout