apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-pvc
  namespace: jhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-db-dir
  namespace: jhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path