hub:
  config:
    JupyterHub:
      authenticator_class: dummy
      shutdown_on_logout: True
      proxy_api_ip: 0.0.0.0
      proxy_api_port: 8001
      bind_url: http://0.0.0.0:8081
      hub_ip: 0.0.0.0
      hub_port: 8081
      log_level: DEBUG
    KubeSpawner:
      k8s_api_request_timeout: 60
      start_timeout: 120
      http_timeout: 60
      pod_pending_timeout: 180
      image_pull_timeout: 120
      hub_connect_url: http://hub.jhub.svc.cluster.local:8081
    Authenticator:
      admin_users:
        - admin
  service:
    type: ClusterIP
    ports:
      nodePort:
  db:
    url: sqlite:////data/jupyterhub.sqlite
  extraVolumes:
    - name: jupyterhub-db
      persistentVolumeClaim:
        claimName: hub-db-dir
  extraVolumeMounts:
    - name: jupyterhub-db
      mountPath: /data

proxy:
  secretToken: "c413fe27d65c5916b7cf4028bf49a19b3056d59f2c2d1e79349244a6f758babe"
  https:
    enabled: false
  service:
    type: ClusterIP

singleuser:
  image:
    name: "danielcristh0/jupyterlab"
    tag: "1.1"
    pullPolicy: Always
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    JUPYTERHUB_LOG_LEVEL: "DEBUG"
    JUPYTERHUB_CLIENT_MAX_RETRIES: "10"
    JUPYTERHUB_CLIENT_CONNECT_IP: "hub.jhub.svc.cluster.local"
  storage:
    capacity: 1G
    dynamic:
      pvcNameTemplate: claim-{username}
      storageAccessModes: ["ReadWriteOnce"]
  memory:
    guarantee: 512M
    limit: 1G
  cpu:
    guarantee: 0.5
    limit: 1

cull:
  enabled: true
  timeout: 600
  every: 60