#cloud-config
hostname: master
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$RANDOM.SALT$Ex8GkBNroM9BAnAOhq6JtL6zGdHuGpqOCZDIvN2RObMdCbl37MfB99TfGFM00eBaD3SkbXn8XhJ0F4UJLUFZL0"  # password: ubuntu123

chpasswd:
  expire: false

ssh_pwauth: true

package_update: true
package_upgrade: true
