---
- name: Setup Master
  hosts: rpl-master
  become: true
  remote_user: ray
  roles:
    - config
    # - docker
    - master
    - manage-cluster

- name: Setup Worker
  hosts:
    - rpl-worker-1
    - rpl-worker-2
  become: true
  remote_user: ray
  roles:
    - config
    - worker