hub:
  config:
    JupyterHub:
      authenticator_class: dummy
      shutdown_on_logout: true
      bind_url: http://0.0.0.0:8081
    KubeSpawner:
      k8s_api_request_timeout: 60
      start_timeout: 300
      http_timeout: 300
    Authenticator:
      admin_users:
        - admin

  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 6

  db:
    url: sqlite:////data/jupyterhub.sqlite

  service:
    type: ClusterIP

  extraVolumes:
    - name: jupyterhub-db
      persistentVolumeClaim:
        claimName: jupyterhub-pvc

  extraVolumeMounts:
    - name: jupyterhub-db
      mountPath: /data

proxy:
  secretToken: "c413fe27d65c5916b7cf4028bf49a19b3056d59f2c2d1e79349244a6f758babe"
  https:
    enabled: false
  service:
    type: ClusterIP

singleuser:
  image:
    name: "danielcristh0/jupyterlab"
    tag: "rpl"
    pullPolicy: Always
  defaultUrl: "/lab"
  storage:
    capacity: 1G
    dynamic:
      pvcNameTemplate: claim-{username}
      storageAccessModes: ["ReadWriteOnce"]
  memory:
    guarantee: 512M
    limit: 2G
  cpu:
    guarantee: 0.5
    limit: 2

cull:
  enabled: true
  timeout: 1800       # menaikkan timeout ke 30 menit
  every: 60
  maxAge: 0
  users: false
  removeNamedServers: false

prePuller:
  hook:
    enabled: false
