apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  containers:
    - name: nvidia-container
      image: nvidia/cuda:12.2.0-base
      command: [ "nvidia-smi" ]
      resources:
        limits:
          nvidia.com/gpu: 1