---
- name: Ensure python3-venv is installed
  apt:
    name: python3-venv
    state: present
  become: true

- name: Create Python virtual environment for Ray
  command: python3 -m venv /opt/ray-env
  args:
    creates: /opt/ray-env

- name: Install kubernetes library for Python using virtualenv
  command: /opt/ray-env/bin/pip install kubernetes

# - name: Clone ray project
#   changed_when: false
#   ansible.builtin.git:
#     repo: https://github.com/danielcristho/k3s-ray-jupyterlab.git
#     dest: /home/daniel/k3s-ray-jupyterlab
#     clone: true

- name: Config Git global safe directory
  ansible.builtin.command: git config --global --add safe.directory /home/daniel/ray-jupyterlab-k3
  args:
    creates: /home/daniel/.gitconfig
  become: true

- name: Install calico network plugin
  kubernetes.core.k8s:
    kubeconfig: /home/daniel/.kube/config
    src: /home/daniel/k3s-ray-jupyterlab/rpl/infra/kubernetes/base/manifests/networks/calico.yaml
    state: present